[tool.poetry]
name = "just-about-sockets"
version = "0.1.0"
description = ""
authors = ["alaev <alaev.musost@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
